### PR TITLE
pull mean from query 

### LINKED ISSUE #387: implement mean zscore call for geneset editor
- https://xenago.xenahubs.net/docs/contents.html

```
diff --git a/src/functions/FetchFunctions.js b/src/functions/FetchFunctions.js
index 2048480..0f21ca0 100644
--- a/src/functions/FetchFunctions.js
+++ b/src/functions/FetchFunctions.js
@@ -12,7 +12,58 @@ import {FILTER_ENUM} from '../components/FilterSelector';
 import {UNASSIGNED_SUBTYPE} from '../components/SubCohortSelector';
 import DefaultPathWays from '../data/genesets/tgac';
 
-const { datasetSamples, datasetFetch, sparseData , datasetProbeValues } = xenaQuery;
+const { xenaPost, datasetSamples, datasetFetch, sparseData , datasetProbeValues } = xenaQuery;
+
+const allFieldMeanQuery =
+	'; allFieldMean\n' +
+	'(fn [dataset samples]\n' +
+	'  (let [fields (map :name (query {:select [:field.name]\n' +
+	'                                  :from [:field]\n' +
+	'                                  :join [:dataset [:= :dataset.id :dataset_id]]\n' +
+	'                                  :where [:and [:= :dataset.name dataset] [:<> :field.name "sampleID"]]}))\n' +
+	'        data (fetch [{:table dataset\n' +
+	'                      :columns fields\n' +
+	'                      :samples samples}])]\n' +
+	'  {:field fields\n' +
+	'   :mean (map car (mean data 1))}))';
+
+const quote = x => '"' + x + '"';
+
+export function allFieldMean(host, dataset, samples) {
+	const query = `(${allFieldMeanQuery} ${quote(dataset)} [${samples.map(quote).join(' ')}])`;
+	return Rx.Observable.ajax(xenaPost(host, query)).map(xhr => JSON.parse(xhr.response));
+}
+
+/////// demo
+const demoSamples = [
+	"TCGA-AB-2815-03",
+	"TCGA-AB-2817-03",
+	"TCGA-AB-2818-03",
+	"TCGA-AB-2819-03",
+	"TCGA-AB-2820-03",
+	"TCGA-AB-2821-03",
+	"TCGA-AB-2822-03",
+	"TCGA-AB-2823-03",
+	"TCGA-AB-2825-03",
+	"TCGA-AB-2826-03",
+	"TCGA-AB-2828-03",
+	"TCGA-AB-2830-03",
+	"TCGA-AB-2834-03",
+	"TCGA-AB-2835-03",
+	"TCGA-AB-2836-03",
+	"TCGA-AB-2839-03",
+	"TCGA-AB-2840-03",
+	"TCGA-AB-2841-03",
+	"TCGA-AB-2842-03",
+	"TCGA-AB-2843-03"
+];
+
+allFieldMean("https://xenago.xenahubs.net", "expr_tpm/TCGA-LAML_tpm_tab.tsv", demoSamples).subscribe(data => {
+	console.log("demo data");
+	console.log(data);
+});
+
+///////
 
 export function getSamplesForCohort(cohort,filter) {
   // scrunches the two
```

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #387

### CODE REVIEW

**Comment by nathandunn** [comment]
Original demo code:

https://github.com/ucscXena/XenaGoWidget/pull/390/files#diff-5cf8574222e3e885fc6ec347b312aa43R147-R198

Generates query:

```
(; allFieldMean
(fn [dataset samples]
  (let [fields (map :name (query {:select [:field.name]
                                  :from [:field]
                                  :join [:dataset [:= :dataset.id :dataset_id]]
                                  :where [:and [:= :dataset.name dataset] [:<> :field.name "sampleID"]]}))
        data (fetch [{:table dataset
                      :columns fields
                      :samples samples}])]
  {:field fields
   :mean (map car (mean data 1))})) "expr_tpm/TCGA-LAML_tpm_tab.tsv" ["TCGA-AB-2815-03" "TCGA-AB-2817-03" "TCGA-AB-2818-03" "TCGA-AB-2819-03" "TCGA-AB-2820-03" "TCGA-AB-2821-03" "TCGA-AB-2822-03" "TCGA-AB-2823-03" "TCGA-AB-2825-03" "TCGA-AB-2826-03" "TCGA-AB-2828-03" "TCGA-AB-2830-03" "TCGA-AB-2834-03" "TCGA-AB-2835-03" "TCGA-AB-2836-03" "TCGA-AB-2839-03" "TCGA-AB-2840-03" "TCGA-AB-2841-03" "TCGA-AB-2842-03" "TCGA-AB-2843-03"])
```

This returns 59K results: 

image

My modified query returns:

```
(; allFieldMean
(fn [dataset samples]
  (let [fields (map :name (query {:select [:field.name]
                                  :from [:field]
                                  :join [:dataset [:= :dataset.id :dataset_id]]
                                  :where [:and [:= :dataset.name dataset] [:<> :field.name "sampleID"]]}))
        data (fetch [{:table dataset
                      :columns fields
                      :samples samples}])]
  {:field fields
   :mean (map car (mean data 1))})) "pathway_act/TCGA_BRCA_BPA_Z.tsv" ["TCGA-3C-AAAU-01,TCGA-3C-AALI-01,TCGA-3C-AALJ-01,TCGA-3C-AALK-01,TCGA-4H-AAAK-01,TCGA-5L-AAT0-01,TCGA-5L-AAT1-01,TCGA-5T-A9QA-01,TCGA-A1-A0SB-01,TCGA-A1-A0SD-01,TCGA-A1-A0SE-01,TCGA-A1-A0SF-01,TCGA-A1-A0SG-01,TCGA-A1-A0SH-01,TCGA-A1-A0SI-01,TCGA-A1-A0SJ-01,TCGA-A1-A0SK-01,TCGA-A
```

returns just the 8K results for `_Z.tsv`

image

FYI @acthp  if you have any thoughts . . . I'll try swapping the cohorts and see if that helps.

**Comment by nathandunn** [comment]
I thunk the problem is that its the wrong query for that dataset,  We'll need to extrapolate to the probe data here:

```
(; datasetProbeValues
(fn [dataset samples probes]
  (let [probemap (:probemap (car (query {:select [:probemap]
                                         :from [:dataset]
                                         :where [:= :name dataset]})))
        position (if probemap
                    (xena-query {:select ["name" "position"] :from [probemap] :where [:in "name" probes]})
                    nil)]
    [position
     (fetch [{:table dataset
              :columns probes
              :samples samples}])]))

 "pathway_act/TCGA_BRCA_BPA_Z.tsv" ["TCGA-3C-AAAU-01" "TCGA-3C-AALI-01" "TCGA-3C-AALJ-01" "TCGA-3C-AALK-01" "TCGA-4H-AAAK-01" "TCGA-5L-AAT0-01" "TCGA-5L-AAT1-01" "TCGA-5T-A9QA-01" "TCG ...
```

**Comment by acthp** [comment]
I think it's the correct query, but the sample list looks like it's not formatted correctly.

```
"TCGA-3C-AAAU-01,TCGA-3C-AALI-01,TCGA-3C-AALJ-01,
```

should be

```
"TCGA-AB-2815-03" "TCGA-AB-2817-03" "TCGA-AB-2818-03" "TCGA-AB-2819-03"
```

**Comment by nathandunn** [comment]
@acthp  I was being boneheaded and I finally got it working:

```
(; allFieldMean
(fn [dataset samples]
  (let [fields (map :name (query {:select [:field.name]
                                  :from [:field]
                                  :join [:dataset [:= :dataset.id :dataset_id]]
                                  :where [:and [:= :dataset.name dataset] [:<> :field.name "sampleID"]]}))
        data (fetch [{:table dataset
                      :columns fields
                      :samples samples}])]
  {:field fields
   :mean (map car (mean data 1))})) "pathway_act/TCGA_LUAD_BPA_Z.tsv"  ["TCGA-05-4244-01" "TCGA-05-4249-01" "TCGA-05-4250-01" "TCGA-05-4382-01" "TCGA-05-4384-01" "TCGA-05-4389-01" "TCGA-05-4390-01" "TCGA-05-4395-01" "TCGA-05-4396-01" "TCGA-05-4397-01" "TCGA-05-4398-01" "TCGA-05-4402-01" "TCGA-05-4403-01" "TCGA-05-4405-01" "TCGA-05-4410-01" "TCGA-05-4415-01" "TCGA-05-4417-01" "TCGA-05-4418-01" "TCGA-05-4420-01" "TCGA-05-4422-01" "TCGA-05-4424-01"
```

**Pull request merged**
