### PR TITLE
Fix jicard 96

### LINKED ISSUE #96: shading for pathway / geneset should use the jicard index
from #71

The shading for the pathways / gene sets should use the [Jicard index](https://en.wikipedia.org/wiki/Jaccard_index) to show overlap intersection of the two sets divided by the union of the two sets.

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #96

### CODE REVIEW

**Comment by nathandunn** [comment]
Original shading (http://xenademo.berkeleybop.io/xena/):

screen shot 2018-09-05 at 7 25 20 am

Jicard index  (http://xenademo.berkeleybop.io/xena-staging/) : 

screen shot 2018-09-05 at 7 25 07 am

**Comment by nathandunn** [comment]
@jingchunzhu  Is this what you had in mind?

**Comment by nathandunn** [comment]
Staging is what is in this PR

**Comment by jingchunzhu** [comment]
The new screenshot using Jicard  index looks more accurate. Thanks.

**Pull request merged**
